export const SOCIAL_LOGIN = 'SOCIAL_LOGIN';
export const SOCIAL_LOGIN_SUCCESS = 'SOCIAL_LOGIN_SUCCESS';
export const SOCIAL_LOGIN_FAILURE = 'SOCIAL_LOGIN_FAILURE';
export const GET_PROFILE = 'GET_PROFILE';
export const UPDATE_USER_PROFILE = 'UPDATE_USER_PROFILE';
export const LOAD_USER_ARTICLES = 'LOAD_USER_ARTICLES';
export const ADD_ARTICLES = 'ADD_ARTICLES';
